language: python
sudo: false

env:
  global:
    - FTP_USER=jpy
    - FTP_HOST=ftp.brockmann-consult.de
    # using http://rkh.github.io/travis-encrypt/public/index.html
    # FTP_PASSWORD
    - secure: g9l0Ksk3qu/+KF2ihaIHLujQdjA4yAtZz8Jlmw80xq0sIq7Lqlqd7Bm98Hkcg+Zdtv8NPCGXmoemfDm48j+lUKluOlnWB9gsWkheWnqG8B8mdzA1QZXGzp32yA3fhWVTkeKbpF4ewcorkR4NfIT/j/BlbeGLQKhLyl8C4DwqpTim7WMHONaStpoEKDK71U2+5uPZ9nERhsEO6M7HBgN+HfkcXihML2YdoHRt8d8FTswgzq4SNe/jgxVLSFoBUS09xHVYIU+oGcNTkcmSb4tgaXgPb83dh6mDR8GtrECRlYK3ZjrVocTp7cC+FdThhMoyfLNcN+Txsep2X98JMLH6BuvIINDdGDoGLUtqf/XVUWi00nSDneQPyHcsr1peovK/CMjq0TMHKp6P2UJVPGZ00aelBXfusfpbh59WeCfDQaOgObZYEJIYav3u27fa8I+0k41Wf11IxUig/jX+0IX4JiIjTBe/0lDxENb0gKBcAbjxjYUAM/Or8RAXRvmf7vFuJpO2n31qFCz7oKT2gzsjDFXyMsNeaWg4YFLZJ+iUjxHUyCg+vyPONohLQjyCUro9fH+dMMyNlM4YvpDjI969EUGnSvkPGtrNHtuuO6ZcOUoZ9xnZpB1nX0XNwXttW0ZDPvFZvDoW0umT1M51l2M8DYg/nh5CpkSMKxfofRs2/No=

# matrix start ###################################

matrix:
  allow_failures:
    - os: osx
  include:
    # Linux -----------------------
    - os: linux
      language: python
      python: 2.7
    - os: linux
      language: python
      python: 3.4
    - os: linux
      language: python
      python: 3.5
    - os: linux
      language: python
      python: 3.6
    # OS-X ------------------------
    # exact versions required (e.g. 3.4 is not available) 
    - os: osx
      language: generic
      env: PYTHON_VERSION='2.7.14'
    - os: osx
      language: generic
      env: PYTHON_VERSION='3.4.7'
    - os: osx
      language: generic
      env: PYTHON_VERSION='3.5.4'
    - os: osx
      language: generic
      env: PYTHON_VERSION='3.6.4'

    # Adding jobs for ppc64le architecture
    - os: linux
      language: python
      python: 3.4
      arch: ppc64le
    - os: linux
      language: python
      python: 3.5
      arch: ppc64le
    - os: linux
      language: python
      python: 3.6
      arch: ppc64le

# matrix end #####################################

cache:
  directories:
    - $HOME/.m2
    - $HOME/.pyenv

addons:
  apt:
    packages:
      # update java8 to latest version
      - oracle-java8-installer
      - oracle-java8-set-default

before_script:
  - travis_wait 20 mvn dependency:resolve
  - bash ./ci/travis/before_script.sh

script:
  - bash ./ci/travis/run.sh
  
after_success:
  # only publish artifacts on master branch when pushed (not from cron or PRs)
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_EVENT_TYPE" = "push" ]; then
      bash ./ci/travis/upload-to-ftp.sh;
    fi
